### ISSUE TITLE
ModuleNotFoundError: No module named 'dbconnections.pytds'

### ISSUE THREAD

**Issue by MichaelJochen** [ikzelf/zbxdb#17]
hi Ronald,when monitoring the sqlserver database with zbxdb, I encountered the following error:
"
2019年 07月 13日 星期六 23:27:02 CST Starting etc/zbxdb.ms_2_206.cfg
INFO:__main__:start python-3.6.5 zbxdb-2.01 pid=17303 Connecting ...

INFO:__main__:zbxdb found db_type=msssql, driver pytds; checking for driver

INFO:__main__:<module 'pytds' from '/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pytds/__init__.py'>
INFO:__main__:zbxdb driver pytds loaded

INFO:__main__:zbxdb driver drivererrors for pytds loaded

CRITICAL:__main__:Failed to load dbconnections routines for msssql

CRITICAL:__main__:Looked in ['/home/zbxdb/zbxdb/bin', '/home/zbxdb/.pyenv/versions/3.6.5/lib/python36.zip', '/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6', '/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6/lib-dynload', '/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6/site-packages']
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 238, in load_db_connections
    "dbconnections." + _c['db_type'])
  File "/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dbconnections.msssql'
CRITICAL:__main__:problem
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 794, in <module>
    main()
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 303, in main
    db_connections = load_db_connections(_config)
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 238, in load_db_connections
    "dbconnections." + _c['db_type'])
  File "/home/zbxdb/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dbconnections.msssql'

"
The contents of the .cfg file are as follows:
"
[zbxdb]
db_url = //172.16.2.206/MSSQLSERVER
username = zbxdb
password =
db_type = msssql
server = hostname.domain
server_port = 1433
db_name = master
db_driver = pytds
role = normal
out_dir = $HOME/zbxora_out
hostname = testhost
checks_dir = etc/zbxdb_checks
site_checks = NONE
instance_type = rdbms
password_enc = U3FsMjAxOQ==
"
The pytds module has been successfully installed and tested as follows：
"
[zbxdb@dhec-vm-264 etc]$ python
Python 3.6.5 (default, Jul 12 2019, 16:13:21)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import pytds
>>>
"
How can I analyze and resolve this issue?
Thank you, I look forward to your reply.

**Comment by MichaelJochen** [comment]
Oh my god, I know why.
look here:
"db_type = msssql"
The correct way is：
”db_type = mssql“
that's all,thanks.
